version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/pascaldekloe/jwt
    steps:
      - checkout
      - run:
          name: Unit Tests
          command: go test -v ./...
